# Generated by Django 5.1.1 on 2025-03-23 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_student_end_time_alter_student_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroom',
            name='parsed_questions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examroom',
            name='question_paper',
            field=models.FileField(blank=True, null=True, upload_to='question_papers/'),
        ),
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
