# Generated by Django 5.1.1 on 2025-03-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_examroom_parsed_questions_examroom_question_paper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentquestion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.student'),
        ),
    ]
